services:
  app:
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: >
      sh -c "
      until yarn sequelize db:migrate; do
        echo 'Waiting for Postgres to be ready...';
        sleep 2;
      done;
      yarn start"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
